@extends('layouts.app')
@section('content')
    @include('subviews.homepage.banner')
    @include('subviews.homepage.book-series')
    @include('subviews.homepage.book-series-showcase')
    @include('subviews.homepage.upcoming-book')
    @include('subviews.homepage.mini-book-browse')
    @include('subviews.newsletter-section')
@endsection